- name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Denna rad tvingar allt till gemener (små bokstäver)
          tags: ghcr.io/professorn3/batterikalkylator:latest
